import { TemplateResult, TemplateInstance } from 'lit';
import { createState, State } from '@lithium-framework/state';
import { _cssObject, CSSObject, createCSS } from './css-object/index';
export { RouterConfiguration, Route, FASTRouter } from '@microsoft/fast-router';
export { html as fasthtml, FASTElement, customElement } from '@microsoft/fast-element';
export { createPage } from './page';
export type ThoriumTemplateResult = TemplateResult & {};
export declare function html(string: TemplateStringsArray, ...args: any[]): ThoriumTemplateResult;
export declare function render(element: TemplateResult, parent?: HTMLElement | DocumentFragment): import("lit-html").RootPart;
export { TemplateInstance };
export { _cssObject, CSSObject, createCSS };
export { createState, State };
export * as Directives from './directives/index';
